name: secret work.
on:
  push:
    branches: [ "main" ]
env:
     name: "Kolya"
jobs:
  stage1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, msg
      - name: print os version
        run: hostnamectl
      - name: Print sha of commit
        run : echo ${{ github.sha }}
  stage2:
    needs: stage1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Show files from repo
        run: ls ${{ github.workspace }}
      - name: Run test.sh
        run: bash test.sh ${{ github.workspace }}
  stage3:
      needs: [ stage1,stage2]
      runs-on: ubuntu-latest
      env:
        local_var: "Bada"
      steps:
      - name: Print Var name
        run: echo "My name is $name"
      - name: Print local var
        run: echo "my last name is $local_var"
        
        
